version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: lfs
      MONGO_INITDB_ROOT_PASSWORD: cin123
      MONGO_INITDB_DATABASE: databaseProd
  
  express-app:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: express-app-container
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
